spring:
  application:
    name: demo-springai-groq

server:
  port: 3000
  servlet:
    context-path: /demo--springai-groq

chat:
  base-url: https://api.groq.com/openai
  api-key: ${GROQ_API_KEY}
  model: llama3-70b-8192
  max-tokens: 1000
  temperature: 0.7